### ISSUE TITLE
How to have multiple PublishConfiguration.ps1 files 

### ISSUE THREAD

**Issue by msgigabyte** [sayedihashimi/package-web#23]
For multiple configs how can I set this file randomly or do I need to have multiple files having settings pointing to test, live. How can I tell it to Publish-Interactive.ps1 file to run which configuration setting. A bit confused. Need to run these using team city. Please guide

Apologies for raising it in issues. as couldn't find the right place to ask a question

**Comment by sayedihashimi** [comment]
Hi no problem I think this is the right place for this.

By default the script will look for PublishConfiguration.ps1 but you can override that with the parameter publishConfigExpectedFilename. This was implemented as a part of issue #17 (https://github.com/sayedihashimi/package-web/pull/17). In your case you can create different files, for example; publish.config.QA01.ps1, publish.config.QA02.ps1, etc. Then just pass in those files when calling publish-interactive.ps1.

I'm going to close this issue but if you think that I missed it, please provide more details and re-open.

**Comment by msgigabyte** [comment]
thank you so much for the reply. I am trying to run this script using teamcity. but unable to pass the parameter. Following is the syntax I am using 
-NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command .\Publish-Interactive.ps1 "PublishConfiguration1.ps1"
 can you please guide.
