### ISSUE TITLE
How to make configuration parameters available on remote machine

### ISSUE THREAD

**Issue by msgigabyte** [sayedihashimi/package-web#24]
I have a question that obj\Debug\Package folder is created on run time when you run a build using teamcity on some agent. If you have test.ps1, Dev.ps1, live.ps1 parameter files for Publish-Interactive.ps1 then with a clean build they will be no longer present. how to keep those settings and pass them to Publish-Interactive.ps1 file on run time. Please guide. really sorry as I am a novice and getting time to understand this. regards

**Comment by sayedihashimi** [comment]
Hi I'm not sure I fully understand your question but will try anyways. If you have files such as test.ps1, dev.ps1, etc and need to make those available in a build server then they need to be checked into source control somewhere. After they are checked in you can customize your build process to pick the files up and place them in the correct directories.

**Comment by msgigabyte** [comment]
Thank you so much for you reply.
