### ISSUE TITLE
 "The target "CopyTransformFilesWap" does not exist in the project" on TFS Build Server with VS2010

### ISSUE THREAD

**Issue by robertmuehsig** [sayedihashimi/package-web#26]
Just tried the PackageWeb and it worked well on my workstation (Win7, VS2010), but failed on my TFS Build Server (with VS2010) . I get this error: 

 C:\Program Files\MSBuild\Microsoft\VisualStudio\v10.0\Web\Microsoft.Web.Publishing.targets (1690): The target "CopyTransformFilesWap" does not exist in the project.

The target is called in the "Sedodream.Package.targets" on line 29. I couldn't figure out where this target is defined so I now have a broken build ;-)

**Comment by sayedihashimi** [comment]
I just made a change to address this. Can you update the package and try again?

FYI if you are blocked with your build you can uninstall the package if you need to revert back to what you had before.

**Comment by robertmuehsig** [comment]
This one is fixed: No Build Error so far. But the powershell script is not in the output of TFS Build - I will open another issue.  
BTW: I just commented the *.wpp.targets stuff out.
