### ISSUE TITLE
web.config's missing after publish

### ISSUE THREAD

**Issue by robertmuehsig** [sayedihashimi/package-web#28]
After I ran the Publish-Interactive.ps1 script all *.configs are gone. If I deploy the same package via VS everything is fine. 

Missing files:
web.config in root folder
~/Views/web.config
some other .config files I added as "content" in my project. 

Any ideas what happend?

**Comment by sayedihashimi** [comment]
There is a skip command passed to msdeploy.exe to prevent transforms from being published. It should not impact web.config, and especially not other .config files.

Can you clarify what you mean by the files are gone? Did you mean the files are not published, or the source files are deleted?

**Comment by robertmuehsig** [comment]
The source files (= files that are already published on the server) are gone after I execute the powershell. I will try to create a demo project.

**Comment by sayedihashimi** [comment]
Hey Robert I looked into it a bit and realized that I was not passing in -enableRule:doNotDelete. I've made a fix and released a new version (1.14) can you try it out and let me know if it resolves the issue for you?

**Comment by sayedihashimi** [comment]
Closing this as it should be fixed. Please re-open if that's not the case.
