### ISSUE TITLE
Publish-Interactive.ps1 not output to correct location using msbuild with /P:PackageLocation

### ISSUE THREAD

**Issue by evgit** [sayedihashimi/package-web#40]
Using vs10 and msbuild

Publish-Interactive is always output to the obj folder, standard package files located at the PackageLocation specified by the msbuild command line.

**Comment by sayedihashimi** [comment]
@evgit could you provide specific repro steps that I could follow? I want to make sure that I'm investigate the particular issue you are having.

**Comment by evgit** [comment]
run msbuild  from command name with /P:PackageLocation, our command line is:

C:/Windows/Microsoft.NET/Framework/v4.0.30319/msbuild.exe" "MyProject.csproj" /T:Package /P:Configuration=Release /P:PackageLocation="C:/MyOtherFolder/NewProjectName.zip" /v:m /nr:false /P:warn=0 /nologo

It is a fairly large C# .Net Web Application, we do have our own custom .wpp,targets file which we use to set file access control on a few folders. I guess there is a potential for conflict there.

I can't track down why, but at some point after raising the issue, it seems to be moving the publish script to the right location now. 

Contents of our wpp.targets file:

```
    <?xml version="1.0" encoding="UTF-8"?>
    <Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">
      <ItemGroup>
        <CustomDirAcl Include="App_Data">
           <AclAccess>Write,Modify</AclAccess>
      </CustomDirAcl>
      <CustomDirAcl Include="Logs">
         <AclAccess>Write,Modify</AclAccess>
      </CustomDirAcl>
      <CustomDirAcl Include="Uploads">
         <AclAccess>Write,Modify</AclAccess>
      </CustomDirAcl>
      <CustomDirAcl Include="images">
         <AclAccess>Write,Modify</AclAccess>
      </CustomDirAcl>
   </ItemGroup>
   <Target Name="SetupCustomAcls" AfterTargets="AddIisSettingAndFileContentsToSourceManifest">
      <ItemGroup>
         <MsDeploySourceManifest Include="setAcl">
            <Path>$(_MSDeployDirPath_FullPath)\%(CustomDirAcl.Identity)</Path>
            <setAclAccess>%(CustomDirAcl.AclAccess)</setAclAccess>
            <setAclResourceType>Directory</setAclResourceType>
            <AdditionalProviderSettings>setAclResourceType;setAclAccess</AdditionalProviderSettings>
         </MsDeploySourceManifest>
      </ItemGroup>
   </Target>
   <Target Name="DeclareCustomParameters" AfterTargets="AddIisAndContentDeclareParametersItems">
      <ItemGroup>
         <MsDeployDeclareParameters Include="SetAcl %(CustomDirAcl.Identity)">
            <Kind>ProviderPath</Kind>
            <Scope>setAcl</Scope>
            <Match>^$(_EscapeRegEx_MSDeployDirPath)\\@(CustomDirAcl)$</Match>
            <DefaultValue>{$(_MsDeployParameterNameForContentPath)}/@(CustomDirAcl)</DefaultValue>
            <Value>$(_DestinationContentPath)/@(CustomDirAcl)</Value>
            <Tags>Hidden</Tags>
            <Priority>$(VsSetAclPriority)</Priority>
            <ExcludeFromSetParameter>True</ExcludeFromSetParameter>
         </MsDeployDeclareParameters>
      </ItemGroup>
   </Target>
</Project>
```

**Comment by sayedihashimi** [comment]
I just tried it and did not have any issues, the .ps1 file was generated in the correct location. I will close this item, but if you do get to a good set of repro steps please re-open this.

On an alternate note you should add /t:"Build;Package" to ensure that the Build target is also invoked.
