### ISSUE TITLE
Ability to set DoNotDelete web deploy rule

### ISSUE THREAD

**Issue by tbehunin** [sayedihashimi/package-web#50]
Right now, PackageWeb defaults the DoNotDelete rule to true with no ability to change that. Looks like the code has a "todo" comment in place to build that feature in, but hasn't yet happened. This is just a placeholder to track that feature.

**Comment by sayedihashimi** [comment]
Fixed it. I have a drop at https://dl.dropbox.com/u/40134810/PackageWeb/issue-50/PackageWeb.1.1.8.12.zip. It will be in the next release.

If you encounter any issues with the drop please re-open this.

To use this in PublishConfiguration.ps1 add the following to

```
    $settingsFromUser += @{name="MSDeployDoNotDelete";value='false'}
```
