### ISSUE TITLE
Targets file needs to be manually included in project file in order for a build server to perform config transforms 

### ISSUE THREAD

**Issue by keithl8041** [sayedihashimi/package-web#52]
Experiencing the same issue with SlowCheetah (http://sedodream.com/2012/12/24/SlowCheetahBuildServerSupportUpdated.aspx), however I feel that editing the msbuild file manually to include the targets file is a better solution than running a dummy project build, so that's what I've done.

Added the following to my web .csproj file, now it works like a dream. 

`<Import Project="_Package\Sedodream.Package.targets" />`

**Comment by sayedihashimi** [comment]
Thanks for the comments, the .targets file is now published with NuGet. If you want you can just check in the .targets file under the packages\ folder. Then you will achieve the same result as what you have suggested.
