### ISSUE TITLE
Configs that are two characters or less are ignored in Publish-Interactive.ps1

### ISSUE THREAD

**Issue by mattgartman** [sayedihashimi/package-web#55]
If you have two letter Config names (ex. QA) they are ignored by the Publish-Interactive.ps1 script.  In the GetTarnsforms() function you are dropping any configs that are two characters or less in line 101:

```
        if( $tName -is [string] -and $tName.length -gt 2 ) {
```

**Comment by sayedihashimi** [comment]
I've checked in the fix for this. Take a look at my checkin notes for d2a26d2ddc3cd029df27fe8e3cfa6a96c959ef8b for instructions on how to try it out.

If you try it and let me know if it works for you I would appreciate it.
