### ISSUE TITLE
Unable to resolve relative paths within project while running test from nunit 3.0 console

### ISSUE THREAD

**Issue by msgigabyte** [sayedihashimi/package-web#81]
Please check issue already raised in stackoverflow.com as http://stackoverflow.com/questions/32988217/unable-to-run-nunit-3-0-tests-from-teamcity

Problem is when running tests using nunit console it is not resolving the relative paths correctly even Run test from field is referring to correct dll path. PLease advice how to resolve this.

**Comment by sayedihashimi** [comment]
What does that have to do with PackageWeb?

**Comment by msgigabyte** [comment]
Sorry My mistake, I clicked on main issues link and it somehow posted here. Apologies.
